"""add deal history table

Revision ID: 3021a692a5b7
Revises: 4f20a67fe992
Create Date: 2026-07-30 15:46:45.521264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3021a692a5b7'
down_revision: Union[str, Sequence[str], None] = '4f20a67fe992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('deal_type', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year', sa.String(length=255), nullable=False),
    sa.Column('vin', sa.String(length=255), nullable=True),
    sa.Column('seller_name', sa.Text(), nullable=False),
    sa.Column('seller_phone', sa.Text(), nullable=False),
    sa.Column('buyer_name', sa.Text(), nullable=True),
    sa.Column('buyer_phone', sa.Text(), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('employee_name', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('date_closed', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deal_history')
    # ### end Alembic commands ###
