"""add employees table and client employee_id

Revision ID: 3ca6ee515cb3
Revises: d74bc2667578
Create Date: 2026-07-28 19:26:56.264861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca6ee515cb3'
down_revision: Union[str, Sequence[str], None] = 'd74bc2667578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clients', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key('clients_employee_id_fkey', 'clients', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('clients_employee_id_fkey', 'clients', type_='foreignkey')
    op.drop_column('clients', 'employee_id')
    op.drop_table('employees')
    # ### end Alembic commands ###
