"""add trim_level to listings

Revision ID: 406d1c6c960e
Revises: ee98bd8fdedf
Create Date: 2026-07-28 03:39:02.961075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406d1c6c960e'
down_revision: Union[str, Sequence[str], None] = 'ee98bd8fdedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('trim_level', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'trim_level')
    # ### end Alembic commands ###
