"""add currency settings to companies

Revision ID: 4873c2358fac
Revises: 1c02820b2c14
Create Date: 2026-07-30 09:17:13.872114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4873c2358fac'
down_revision: Union[str, Sequence[str], None] = '1c02820b2c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('rate_source', sa.String(length=10), server_default='auto', nullable=False))
    op.add_column('companies', sa.Column('manual_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('companies', sa.Column('cached_auto_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('companies', sa.Column('cached_auto_rate_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'cached_auto_rate_fetched_at')
    op.drop_column('companies', 'cached_auto_rate')
    op.drop_column('companies', 'manual_rate')
    op.drop_column('companies', 'rate_source')
    # ### end Alembic commands ###
