"""add cancellation reason to employee invites

Revision ID: 4f20a67fe992
Revises: 4873c2358fac
Create Date: 2026-07-30 13:34:02.459903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f20a67fe992'
down_revision: Union[str, Sequence[str], None] = '4873c2358fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_invites', sa.Column('cancellation_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_invites', 'cancellation_reason')
    # ### end Alembic commands ###
