"""add mileage to service_records

Revision ID: 57a3fb8bfb29
Revises: 759014f2899e
Create Date: 2026-07-27 01:27:53.602857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a3fb8bfb29'
down_revision: Union[str, Sequence[str], None] = '759014f2899e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('service_records', sa.Column('mileage', sa.Integer(), nullable=True))
    op.execute('UPDATE service_records SET mileage = 0 WHERE mileage IS NULL')
    op.alter_column('service_records', 'mileage', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'mileage')
    # ### end Alembic commands ###
