"""add account type and business fields to user

Revision ID: 592b02dcbec0
Revises: 9da758a570b1
Create Date: 2026-07-27 15:14:52.905572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '592b02dcbec0'
down_revision: Union[str, Sequence[str], None] = '9da758a570b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_type', sa.String(length=20), server_default='individual', nullable=False))
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('business_phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('business_tax_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'business_tax_id')
    op.drop_column('users', 'business_phone')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'account_type')
    # ### end Alembic commands ###
