"""add listings table

Revision ID: 983f773fc4be
Revises: 592b02dcbec0
Create Date: 2026-07-27 16:02:37.342907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983f773fc4be'
down_revision: Union[str, Sequence[str], None] = '592b02dcbec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('year', sa.String(length=255), nullable=False),
    sa.Column('mileage', sa.String(length=255), nullable=False),
    sa.Column('vin', sa.String(length=255), nullable=True),
    sa.Column('body_type', sa.String(length=100), nullable=False),
    sa.Column('transmission', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), server_default='petrol', nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=20), server_default='used', nullable=False),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('additional_expenses', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('date_added', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('date_sold', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
