"""add receipt links to service record and fuel refill

Revision ID: 9da758a570b1
Revises: 31503f32e277
Create Date: 2026-07-27 13:11:09.488773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da758a570b1'
down_revision: Union[str, Sequence[str], None] = '31503f32e277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('service_record_id', sa.Integer(), nullable=True))
    op.add_column('receipts', sa.Column('fuel_refill_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'receipts_service_record_id_fkey', 'receipts', 'service_records', ['service_record_id'], ['id'], ondelete='SET NULL'
    )
    op.create_foreign_key(
        'receipts_fuel_refill_id_fkey', 'receipts', 'fuel_refills', ['fuel_refill_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('receipts_fuel_refill_id_fkey', 'receipts', type_='foreignkey')
    op.drop_constraint('receipts_service_record_id_fkey', 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'fuel_refill_id')
    op.drop_column('receipts', 'service_record_id')
    # ### end Alembic commands ###
