"""add unique partial index for one seller per listing

Revision ID: bba2073a31ce
Revises: 9a02c5ccb02f
Create Date: 2026-07-28 14:09:20.801757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba2073a31ce'
down_revision: Union[str, Sequence[str], None] = '9a02c5ccb02f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clients_unique_seller_per_listing', 'clients', ['listing_id'], unique=True, postgresql_where=sa.text("client_type = 'seller'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clients_unique_seller_per_listing', table_name='clients', postgresql_where=sa.text("client_type = 'seller'"))
    # ### end Alembic commands ###
