"""extract service_record_items from service_records

Revision ID: c32415f72258
Revises: db816e87db1b
Create Date: 2026-07-27 02:10:38.292817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c32415f72258'
down_revision: Union[str, Sequence[str], None] = 'db816e87db1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_record_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_record_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_record_id'], ['service_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # backfill: каждая существующая запись становится одной позицией с её текущими description/cost
    op.execute(
        """
        INSERT INTO service_record_items (service_record_id, name, price)
        SELECT id, description, cost FROM service_records
        """
    )

    op.drop_column('service_records', 'cost')
    op.drop_column('service_records', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_records', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('service_records', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_table('service_record_items')
    # ### end Alembic commands ###
