"""add record_type to service_records

Revision ID: db816e87db1b
Revises: 57a3fb8bfb29
Create Date: 2026-07-27 01:53:47.483886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db816e87db1b'
down_revision: Union[str, Sequence[str], None] = '57a3fb8bfb29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_records', sa.Column('record_type', sa.String(length=20), server_default='maintenance', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_records', 'record_type')
    # ### end Alembic commands ###
