"""add fuel_type to cars and fuel_refills table

Revision ID: e2eb6e9a1768
Revises: c32415f72258
Create Date: 2026-07-27 14:31:12.251240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2eb6e9a1768'
down_revision: Union[str, Sequence[str], None] = 'c32415f72258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_refills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('refill_date', sa.Date(), nullable=False),
    sa.Column('fuel_amount', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('station_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cars', sa.Column('fuel_type', sa.String(length=20), server_default='petrol', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'fuel_type')
    op.drop_table('fuel_refills')
    # ### end Alembic commands ###
