"""drop listings original_price column

Revision ID: ee98bd8fdedf
Revises: 983f773fc4be
Create Date: 2026-07-28 02:07:25.354136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee98bd8fdedf'
down_revision: Union[str, Sequence[str], None] = '983f773fc4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'original_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('original_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
